

INSERT INTO `tb_book` (title, book_year, book_language, book_format,book_license,author_name,
                     book_value, num_pages, genre,
                     rating,editora_id, description, created_at) VALUES
 ('Harry Potter and the Philosophers Stone', '1997-01-02','Portuguese', 'DIGITAL','Creative Commons','J.K. Rowling',20.0, 240, 'FANTASY', 4.9, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2023-01-11'),
 ('Smarter Than the Devil','2014-02-12', 'English', 'DIGITAL','Creative Commons' ,'Napoleon Hill',31.0,213, 'NEGOTIATION', 4.7, 1,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2025-12-16'),
 ('The Midnight Library', '2021-10-01', 'Portuguese','PHYSICAL','Copyright','Matt Haig',19.5,260, 'FICTION', 4.6,2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2022-02-12'),
 ('The Animal Revolution','2007-07-21', 'English', 'DIGITAL','Copyright' ,'George Orwell', 35.0, 147, 'FABLE', 4.8, 2,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-07-09'),
 ('The Little Prince - Deluxe Edition','2023-12-15', 'Portuguese','PHYSICAL','Creative Commons','Antonie de Saint-Exupéry', 40.0, 190,'ACTION', 4.9,2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','2023-02-28'),
 ('The Prince- Deluxe Edition','2023-01-02', 'Portuguese','DIGITAL','Creative Commons' ,'Nicolau Maquiavel', 49.5, 150,'PHILOSOPHY', 4.6,1,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','2025-01-12');

